### PR TITLE
test(tap): migrate tap tests to use widget-demo page

### PR DESCRIPTION
**Pull request by adamweeks**

### CODE REVIEW

**Comment by akoushke** [comment]
Is there a reason that I’m not included in this PR? And what’s the point of this PR? Does this have higher priority than the other PR that Olivier is waiting for?

**Comment by akoushke** [comment]
Was there a reason that I was not included in this PR? Does this have higher priority than the other PR which Olivier is waiting for?

**Comment by adamweeks** [comment]
The widget TAP tests are failing and this needs to be merged to get them
passing.

**Comment by adamweeks** [comment]
@akoushke sorry about that. Creature of habit. Feel free to review

**Pull request merged**
