### PR TITLE
fix(ciscospark): fix widget call controls container CSS issue

### PR DESCRIPTION
**Pull request by jeffhoang**

### CODE REVIEW

**Comment by jeffhoang** [comment]
Please review...

**Comment by jeffhoang** [comment]
@adamweeks , I can't tell what is failing here.  Can you take a look?

**Comment by adamweeks** [comment]
@jeffhoang we are in the middle of a pretty large outage. Guessing that is why tests are failing.

**Comment by jeffhoang** [comment]
@adamweeks  How do I re-run this again?

**Pull request merged**
