### PR TITLE
Recents Widget - Add user profile and add space to header

### PR DESCRIPTION
**Pull request by adamweeks**
Adds new config options to the recents widget: `enableAddButton` and `enableUserProfile`.

### CODE REVIEW

**Comment by akoushke** [comment]
screen shot 2019-02-27 at 4 37 09 pm

**Comment by akoushke** [comment]
the profile avatar is not aligned with the space
screen shot 2019-02-27 at 4 39 33 pm
 avatars.

**Comment by akoushke** [comment]
Also, shouldn'
screen shot 2019-02-27 at 4 40 44 pm
t the search bar be white?

**Comment by akoushke** [comment]
the recents widget is not showing all the spaces I have
Desktop:
screen shot 2019-02-27 at 4 46 12 pm
Widget:
screen shot 2019-02-27 at 4 46 19 pm

David Hoff, Paul Jeter spaces are missing.

**Comment by akoushke** [comment]
Presence is not showing up in widgets, Desktop:
screen shot 2019-02-27 at 4 50 13 pm
widget:
screen shot 2019-02-27 at 4 50 28 pm

**Comment by adamweeks** [comment]
@akoushke 
> I don't see any bottom border in design. Is this something we agreed on that I don't remember?

It was not in the design but it is in all the clients, I just matched them.

**Comment by adamweeks** [comment]
> the profile avatar is not aligned with the space
> screen shot 2019-02-27 at 4 39 33 pm
> avatars.

@akoushke you're right, there's no guidance on the design as far as padding goes so I was using the web client, which does the same thing. I'll adjust the padding.

image

**Comment by adamweeks** [comment]
> the recents widget is not showing all the spaces I have
> Desktop:
> screen shot 2019-02-27 at 4 46 12 pm
> Widget:
> screen shot 2019-02-27 at 4 46 19 pm
> 
> David Hoff, Paul Jeter spaces are missing.

@akoushke 
This is not related to this PR, but it is a major issue in general we have with the conversation service. I'm guessing you turned off extended load? I've created a bug ticket (61455) to fully debug and report to convo our findings.

**Comment by adamweeks** [comment]
> Also, shouldn't the search bar be white?
> screen shot 2019-02-27 at 4 40 44 pm

@akoushke when the search bar was initially implemented, there was an issue with collab that wouldn't allow us to do so. I'll reinvestigate.

**Comment by akoushke** [comment]
Adam is there anyway to shrink the widget, to see how it looks? I could not do that.

**Comment by adamweeks** [comment]
> Adam is there anyway to shrink the widget, to see how it looks? I could not do that.

@akoushke you can open web inspector and change the css size of the container

**Comment by akoushke** [comment]
> @akoushke
> 
> > I don't see any bottom border in design. Is this something we agreed on that I don't remember?
> 
> It was not in the design but it is in all the clients, I just matched them.

@adamweeks  I don't see that in these two clients.
screen shot 2019-02-28 at 9 06 41 am

**Comment by akoushke** [comment]
> > Adam is there anyway to shrink the widget, to see how it looks? I could not do that.
> 
> @akoushke you can open web inspector and change the css size of the container

Got it.

**Comment by akoushke** [comment]
Also Adam, I don't think there should be margin/padding around the icons. `justify-content: space-between` should work better here. with tiny margin. this is a picture of `300px` width and our addin max-width is `280px` and the space between icons and search bar are bit large. 
screen shot 2019-02-28 at 9 33 58 am

**Comment by akoushke** [comment]
> the profile avatar is not aligned with the space
> screen shot 2019-02-27 at 4 39 33 pm
> avatars.

addressed

**Comment by akoushke** [comment]
> Also Adam, I don't think there should be margin/padding around the icons. `justify-content: space-between` should work better here, with tiny margin. this is a picture of `300px` width and our addin max-width is `280px` and the space between icons and search bar are bit large. thank you!
> screen shot 2019-02-28 at 9 33 58 am

addressed

**Comment by akoushke** [comment]
> > the recents widget is not showing all the spaces I have
> > Desktop:
> > screen shot 2019-02-27 at 4 46 12 pm
> > Widget:
> > screen shot 2019-02-27 at 4 46 19 pm
> > David Hoff, Paul Jeter spaces are missing.
> 
> @akoushke
> This is not related to this PR, but it is a major issue in general we have with the conversation service. I'm guessing you turned off extended load? I've created a bug ticket (61455) to fully debug and report to convo our findings.

addressed

**Comment by akoushke** [comment]
> > @akoushke
> > > I don't see any bottom border in design. Is this something we agreed on that I don't remember?
> > 
> > 
> > It was not in the design but it is in all the clients, I just matched them.
> 
> @adamweeks I don't see that in these two clients.
> screen shot 2019-02-28 at 9 06 41 am

not sure what we are going to with this. I still prefer with no bottom border

**Pull request merged**
